//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationAttribute.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    [MetadataType(typeof(HiredPerson))]

    
    public partial class HiredPerson
    {
        [Key]
        
        public int ID { get; set; }

        [DataType(DataType.Text)]

        [Required(ErrorMessage = "please enter fullname "), MaxLength(30)]
        [Display(Name = "Hired perso name")]

        public string fullname { get; set; }
        [DisplayFormat(NullDisplayText = "Gender not specified")]
        public string Gender { get; set; }
        [Range(20, 30)]
        public Nullable<int> Age { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "please enter Email ID")]
        [RegularExpression(@"^w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid")]

        public string EmailAddress { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt")]
        public Nullable<System.DateTime> Doj { get; set; }

     
        [Range(10000, 70000, ErrorMessage = "zrange should be 10k to 70k")]
        public Nullable<int> Salary { get; set; }
    }
}
