//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partial_View_Image.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string productname { get; set; }
        public Nullable<int> category_Id { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public string photo { get; set; }
    }
}
