//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grocery_Product
    {
        public int ID { get; set; }
        public string Productname { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> mfd { get; set; }
        public Nullable<int> Catid { get; set; }
    }
}
