//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDB_SQLEntities : DbContext
    {
        public myDB_SQLEntities()
            : base("name=myDB_SQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grocery_Category> Grocery_Category { get; set; }
        public virtual DbSet<Grocery_Product> Grocery_Product { get; set; }
        public virtual DbSet<person_details> person_details { get; set; }
        public virtual DbSet<Shop_category> Shop_category { get; set; }
        public virtual DbSet<Shop_product> Shop_product { get; set; }
    }
}
