//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> MDF { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual Shop_category Shop_category { get; set; }
    }
}
