var a=120;
var b=200;
var result;
var linebreak="<br/>";
result=a & b;
document.write("& ="+result);
console.log(result);
document.write(linebreak);
result=a|b;
document.write("OR ="+result);
console.log(result);
document.write(linebreak);
result=a^b;
document.write("XOR ="+result);
console.log(result);
document.write(linebreak)
result=~b;
document.write("NOT ="+result);
console.log(result);
document.write(linebreak);
result=a<<b;
document.write("Left sheft ="+result);
console.log(result);
document.write(linebreak);
result=a>>b;
document.write("Right Shift ="+result);
console.log(result);
document.write(linebreak);
