//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Web_FormStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiredPerson
    {
        public int ID { get; set; }
        public string fullname { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
