//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospial_MVC_Example.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int id { get; set; }
        public string Doctor_name { get; set; }
        public string hospital_Depart { get; set; }
    }
}
