//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospial_MVC_Example.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    [MetadataType(typeof(Patient))]
    public partial class Patient
    {
        public int id { get; set; }


        [DataType(DataType.Text)]
        [Required(ErrorMessage = "please enter name or max letter allowed"), MaxLength(20)]
        [Display(Name = " patient name")]


        public string PatientName { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> hospital_Code { get; set; }
        public Nullable<int> Primary_doctor_code { get; set; }

            


     }      
}
